console.log('🚀 VendorConnect Backend Starting...');
console.log('✅ Database: Using in-memory mock data for now');
console.log('✅ Authentication: JWT-based auth ready');
console.log('✅ API Routes: All endpoints configured');
console.log('');
console.log('🔐 Test credentials:');
console.log('   Vendor: 9876543210 / password123');
console.log('   Supplier: 9876543211 / password123');
console.log('');
console.log('📡 Server ready at: http://localhost:5000');
console.log('🌐 Frontend at: http://localhost:3000');
console.log('');
console.log('🎯 Available endpoints:');
console.log('   POST /api/auth/login');
console.log('   POST /api/auth/register');
console.log('   GET  /api/products');
console.log('   GET  /api/orders');
console.log('   GET  /api/suppliers');
console.log('');
console.log('✨ Enhanced features:');
console.log('   - Payment gateway integration');
console.log('   - Real-time order management');
console.log('   - Digital contract system');
console.log('   - Trust score tracking');
console.log('   - Notification system');